### ISSUE TITLE
Deployment in Azure doesnt work

### ISSUE THREAD

**Issue by BavarianTools** [OfficeDev/msteams-samples-hello-world-nodejs#5]
Locally npm start works fine , the App is up and running.  

If "Deploy to WebApp" from Visual Studio Code or other Deployment Options are used on the root Folder, Deployment works fine, but if you call the Website you get error 500 internal Server error:

Application has thrown an uncaught exception and is terminated:
Error: Configuration property "bot" is not defined
    at Config.get (D:\home\site\wwwroot\node_modules\config\lib\config.js:202:11)
    at Object.module.exports.setup (D:\home\site\wwwroot\src\bot.js:7:28)
    at Object.<anonymous> (D:\home\site\wwwroot\src\app.js:12:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by mhdsws** [comment]
Hi all :), I have the same issue
